### ISSUE TITLE
ComponentMismatchException on Select

### ISSUE THREAD

**Issue by intellow** [calebporzio/livewire#234] opened 2019-09-03 14:02 UTC
When I wire:model a select to a public property, when I update the select item, the request comes back with a ComponentMismatchException. This started happening after upgrading to 0.3.1.

I tested this with a text input and the text works fine. It's just the select for some reason.

I wanted to make sure it wasn't something else in my complex component, so I created a brand new component and stripped it down to just the select, and am still seeing the issue. Here is what it looks like:

```
class UpdateParticipant extends Component
{
    public $agencyId;
    public $agencies;

    protected $user;

    public function mount($id)
    {
        $this->user = User::with('participant')->findorfail($id);
        $this->agencyId = $this->user->participant->agency_id;
        $this->agencies = Agency::active()->housingProgramOperator()->ordered()->get()->pluck('name', 'id')->toArray();
    }

    public function render()
    {
        return view('livewire.update-participant')
            ->with('participant', $this->user);
    }
}
```

```
<div>
    <div class="form-group col-md-6">
        {!! Form::select('agency', $agencies, $agencyId, [
            'class' => 'form-control selectpicker',
            'title' => 'Agency',
            'required',
            'data-live-search' => 'true',
            'data-style' => 'select-with-transition',
            'data-size' => 5,
            'wire:model' => 'agencyId'
        ]) !!}
        @if($errors->has('agency'))<div class="input-error">{{$errors->first('agency')}} .</div>@endif
    </div>
</div>
```

Here's there error in action:

![2019-09-03_08-58-03 (1)](https://user-images.githubusercontent.com/40676515/64179659-29190f80-ce29-11e9-9b08-5a0abd2c4900.gif)

**Comment by intellow** [comment] 2019-09-03 15:08
I've also confirmed that if I comment out this
```
throw_unless(
    $checksumManager->check($checksum, $component, $id, $publicProperties),
    ComponentMismatchException::class
);
```
and do a single update, then put it back in, everything works. It seems like the initial checksum is being set incorrectly.

**Comment by calebporzio** [comment] 2019-09-03 18:29
Hey @intellow,

I checked with a normal `<select>` and everything works fine.

I imagine there's some weirdness because of you using selectpicker.

Maybe take a look at the initial data that is encoded in the DOM:
![image](https://user-images.githubusercontent.com/3670578/64198931-3d740100-ce57-11e9-874d-a0356efa0d84.png)

and compare it to the data being sent on the first request:
![image](https://user-images.githubusercontent.com/3670578/64198915-351bc600-ce57-11e9-8a55-56dea84e7a97.png)

Post both of those and we can go from there.

**Comment by intrepidws** [comment] 2019-09-03 18:42
@intellow FWIW I was getting this same error when I had properties that were being changed from a string to an empty string. I was able to fix it by instead changing to `null`. Not sure if that helps or not.

**Comment by intellow** [comment] 2019-09-03 18:49
I did this without the selectpicker as well just to remove that variable, and got the same error.
The data seems to be the same, expect it is in a different order.

![image](https://user-images.githubusercontent.com/40676515/64200161-845ef800-ce51-11e9-972a-64b6c6b0862b.png)
![image](https://user-images.githubusercontent.com/40676515/64200170-8759e880-ce51-11e9-9569-fb42371c9943.png)

**Comment by intellow** [comment] 2019-09-03 18:52
@calebporzio I removed the `ordered()` scope on getting the data (which sorts alphabetically by value instead of key), and then everything works. It looks like we need to figure out how to prevent Javascript from changing the order in this issue #160

**Comment by calebporzio** [comment] 2019-09-04 13:24
Should be fixed in v0.3.3: https://github.com/calebporzio/livewire/releases/tag/v0.3.3

Please verify.

**Comment by intellow** [comment] 2019-09-04 16:59
@calebporzio unfortunately this broke everything  😬. Javascript is now taking my primary keys and reindexing them starting from zero. So in my Livewire component I have something like this:

![image](https://user-images.githubusercontent.com/40676515/64275405-124ae980-cf0b-11e9-8343-db1de2a03747.png)

And in the web browser I get this:

![image](https://user-images.githubusercontent.com/40676515/64275515-4faf7700-cf0b-11e9-8c8b-c7e8f1380614.png)

**Comment by calebporzio** [comment] 2019-09-05 11:52
Oh boy, that is certainly my fault for misunderstanding the problem.

My thinking was, because `JSON.parse` is going to order all numeric keys, then I'll set the proper indexes on the PHP side to prevent that.

I'm not sure we will find a good way to preserve numerically indexed arrays from PHP to JavaScript, without JavaScript re-ordering them.

In light of that, what do you think is the best behavior?

Also, why don't the `<option>`s show up in order of numeric key? the order seems arbitrary in the DOM.

**Comment by intellow** [comment] 2019-09-05 15:28
I think you're right, it seems that if order is important on the front end then we'd have to use javascript to do the sorting. At a minimum, this can be accomplished by the user writing their own sorting method and then using the javascript lifecycle hook
 ```
window.livewire.afterDomUpdate(() => {
    // Add your javascript sort function here.
});
```
I think the biggest issue right now is the checksum. If someone does try to order their key-value pair in any way except ordered by key, it seems the checksum will fail.

I'm not sure why the options are ordered strangely.

**Comment by intellow** [comment] 2019-09-10 03:56
Are you planning to do make any changes to either remove this functionality you added or add some kind of flag to bypass it? I am stuck at 0.3.2 because I can't upgrade to a version where my keys get overwritten.

**Comment by brandonpittman** [comment] 2019-09-11 07:42
I found that resetting a public prop to an empty string caused data mismatches as well. Setting to `null` works however.

**Comment by calebporzio** [comment] 2019-09-11 15:58
@brandonpittman - that was a bug caused by Laravel's TrimStrings and ConvertEmptyStringsToNull middlewares. I just tagged a release that bypasses them for Livewire requests: v0.3.5

**Comment by calebporzio** [comment] 2019-09-11 16:00
@intellow - yeah, resolving this is definitely a high priority. I'm heading out of town for the weekend, so I will try to tackle this next week.

As I see it, it's more important to not mess with the array indexes than to have the orders of numeric indexes preserved (like I believe you mentioned).

So, I think we need to implement a solution that exactly mirrors the behavior of JSON.parse for now (which would mess with the order of numeric indexes, but not modify them). Then explore solutions, but just to get passed this for now.

What do you think?

**Comment by calebporzio** [comment] 2019-09-19 16:43
@intellow, the latest tag (v0.3.6) removed the array index overriding, so that shouldn't be happening anymore. I basically made the initial data transformation, match what JSON.parse will do, so the array ordering will still not be preserved with numeric indexes, but at least there won't be any ComponentMismatch errors or index overwriting.

**Closed by calebporzio** 2019-09-19 16:43 UTC
